### PR TITLE
Implement security module

### PR DESCRIPTION
**Pull request by giovanifss**
Pull request for discussions about the development of security funcionalities.

### CODE REVIEW

**Comment by giovanifss** [comment]
Security Manager must be split in two different classes: SecurityController and ContextManager. SecurityController will be responsible for validate the request and ContextManager will be responsible for manage the context. The context document was defined and each attribute will become a function. Attributes for first implementation:
- expiration time: timestamp
- connection time: int (ms)
- fishy count: int
- request frequency: double
- constancy: double
- completeness: double

To not disrupt the data flow, ContextManager will always be executed in a separated thread. So the data flows normally and the context is updated separately.

**Comment by sant0ro** [comment]
@CaioMeloSilva autorize o PR.

**Comment by giovanifss** [comment]
@sant0ro não é pra aceitar ainda não. Vc pode ver que tem uma label "Work-in-Progress". Só tá aberta pra manter o histórico de discussão sobre a implementação do módulo de segurança no futuro.

**Comment by sant0ro** [comment]
Closing this Issue. Code abandoned.

**Pull request closed without merging**
